version: "3.9"

services:
  web:
    image: node:18-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - NEXT_TELEMETRY_DISABLED=1
    volumes:
      - ./:/app
      - ./.env.development:/app/.env
      # Keep container's node_modules separate from host to avoid conflicts
      - /app/node_modules
    command: sh -c "npm install && npm run dev"